# Generated by Django 3.2.11 on 2022-01-27 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MBTI_Res',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Animal', models.CharField(max_length=100)),
                ('Rides', models.CharField(max_length=100)),
                ('Cnt', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField(default=0)),
                ('Content', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sep_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sep', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.CharField(max_length=100)),
                ('FK_Questions_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.questions')),
                ('FK_Sep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sep_models')),
            ],
        ),
    ]
