# Generated by Django 3.2.11 on 2022-01-28 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mbti_res',
            name='Animal',
        ),
        migrations.RemoveField(
            model_name='mbti_res',
            name='Rides',
        ),
    ]
