# Generated by Django 3.2.11 on 2022-01-28 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220128_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbti_res',
            name='Data_res',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
